### ISSUE TITLE
Add Label for "Group"

### ISSUE THREAD

**Issue by SibylSchaefer** [Chronopolis-Digital-Preservation/audit-control-environment#2]
It is confusing to determine which is the Collection Name and which is the Group Name. A label should be added for the Group Name. This could potentially be added near the top of the table, under Collection Name but left-aligned so the Group Names fall under that label.

**Comment by lsitu** [comment]
@SibylSchaefer Here are the screenshots for those two options (Group label on top of the group name, and Group label in front of the group name) that we can have for the Group label. Just let me know which way you like better and I can adjust it. Thanks.

- Group label on top of the Group Names (current implementation):
Group opened:
<img width="1439" alt="Screen Shot - ACE Group label open" src="https://user-images.githubusercontent.com/2430784/158477208-3b68821b-73dc-4c82-9cb2-aebc0d2c9d9a.png">

Group collapsed:
<img width="1438" alt="Screen Shot - ACE group label closed" src="https://user-images.githubusercontent.com/2430784/158477598-bbed2bc7-16da-4d72-a2c5-714560be69fd.png">


- Group label in front of the Group Names
Group opened
<img width="1440" alt="Screen Shot - ACE group label open-2" src="https://user-images.githubusercontent.com/2430784/158477742-71fc455d-ba09-4ef5-8a03-16464b60e642.png">

Group collapsed:
<img width="1440" alt="Screen Shot - ACE group label closed-2" src="https://user-images.githubusercontent.com/2430784/158477802-8d8de069-e84b-4259-b1f2-5efbd7fc0dbf.png">

**Comment by SibylSchaefer** [comment]
I think the Collection Name label is throwing this off. Could we remove that and place Group Name there instead? That way it makes more sense when it is collapsed.

**Comment by lsitu** [comment]
@SibylSchaefer Sure. And I've created MR https://github.com/Chronopolis-Digital-Preservation/audit-control-environment/pull/20 to adjust. Would you take a look? Thanks.

**Comment by SibylSchaefer** [comment]
Fixed version 1.15.0
