### ISSUE TITLE
Include size and audit time period columns for collections

### ISSUE THREAD

**Issue by SibylSchaefer** [Chronopolis-Digital-Preservation/audit-control-environment#3]
It would be helpful to know how large the individual collections are (rather than having just the group size listed). It would also be useful to see what the audit time period for each collection is.

**Comment by lsitu** [comment]
@SibylSchaefer @rstanonik It looks like we already have the `Last Audit` column for the audit finish time (see attachment). What do we want to display in the `audit time period` column, a time range for audit with start time and finish time, or the actual time in [days | hours | minutes | seconds] that an audit took? 

<img width="1440" alt="Screen Shot - ace-status-page" src="https://user-images.githubusercontent.com/2430784/158431425-d250f0eb-de7a-4417-9d52-7cb86dd81bcd.png">

**Comment by lsitu** [comment]
@SibylSchaefer @rstanonik Just let you know that I've found that piece for audit period, which is counted in days. And we can just utilized it. Thanks.

**Comment by SibylSchaefer** [comment]
Fixed version 1.15.0
